services:
  - type: web
    name: streak-it-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install --prefix server
    startCommand: node server/server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_ORIGIN
        sync: false
      - key: MONGODB_URI
        sync: false
